export const SET_SWEET_SPOT_POSITION = 'SET_SWEET_SPOT_POSITION';
export const SET_SWEET_SPOT_DIRECTION = 'SET_SWEET_SPOT_DIRECTION';
export const SET_SPEAKER_SPAN = 'SET_SPEAKER_SPAN';
export const SET_ROOM_DIMENSIONS = 'SET_ROOM_DIMENSIONS';
export const SET_MIN_WALL_OFFSET = 'SET_MIN_WALL_OFFSET';
export const SET_UNIT_OF_MEASURE = 'SET_UNIT_OF_MEASURE';